/**
 * 错误码定义
 * 格式：模块_错误类型_具体错误
 * 例如：AUTH_INVALID_TOKEN, VALIDATION_REQUIRED_FIELD
 */
export enum ErrorCode {
  // 通用错误 (1000-1999)
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  INVALID_REQUEST = 'INVALID_REQUEST',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED',

  // 认证错误 (2000-2999)
  AUTH_REQUIRED = 'AUTH_REQUIRED',
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_INSUFFICIENT_PERMISSIONS = 'AUTH_INSUFFICIENT_PERMISSIONS',

  // 验证错误 (3000-3999)
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  VALIDATION_REQUIRED_FIELD = 'VALIDATION_REQUIRED_FIELD',
  VALIDATION_INVALID_FORMAT = 'VALIDATION_INVALID_FORMAT',
  VALIDATION_OUT_OF_RANGE = 'VALIDATION_OUT_OF_RANGE',

  // OAuth2 错误 (4000-4999)
  OAUTH2_INVALID_CLIENT = 'OAUTH2_INVALID_CLIENT',
  OAUTH2_INVALID_GRANT = 'OAUTH2_INVALID_GRANT',
  OAUTH2_INVALID_SCOPE = 'OAUTH2_INVALID_SCOPE',
  OAUTH2_INVALID_REDIRECT_URI = 'OAUTH2_INVALID_REDIRECT_URI',
  OAUTH2_UNSUPPORTED_GRANT_TYPE = 'OAUTH2_UNSUPPORTED_GRANT_TYPE',
}

/**
 * 错误码到 HTTP 状态码的映射
 */
export const ERROR_CODE_TO_STATUS: Record<ErrorCode, number> = {
  [ErrorCode.INTERNAL_ERROR]: 500,
  [ErrorCode.INVALID_REQUEST]: 400,
  [ErrorCode.RESOURCE_NOT_FOUND]: 404,
  [ErrorCode.METHOD_NOT_ALLOWED]: 405,
  [ErrorCode.AUTH_REQUIRED]: 401,
  [ErrorCode.AUTH_INVALID_TOKEN]: 401,
  [ErrorCode.AUTH_TOKEN_EXPIRED]: 401,
  [ErrorCode.AUTH_INSUFFICIENT_PERMISSIONS]: 403,
  [ErrorCode.VALIDATION_FAILED]: 400,
  [ErrorCode.VALIDATION_REQUIRED_FIELD]: 400,
  [ErrorCode.VALIDATION_INVALID_FORMAT]: 400,
  [ErrorCode.VALIDATION_OUT_OF_RANGE]: 400,
  [ErrorCode.OAUTH2_INVALID_CLIENT]: 400,
  [ErrorCode.OAUTH2_INVALID_GRANT]: 400,
  [ErrorCode.OAUTH2_INVALID_SCOPE]: 400,
  [ErrorCode.OAUTH2_INVALID_REDIRECT_URI]: 400,
  [ErrorCode.OAUTH2_UNSUPPORTED_GRANT_TYPE]: 400,
};

/**
 * 错误码的默认消息（英文）
 */
export const ERROR_CODE_MESSAGES: Record<ErrorCode, string> = {
  [ErrorCode.INTERNAL_ERROR]: 'Internal Server Error',
  [ErrorCode.INVALID_REQUEST]: 'Invalid Request',
  [ErrorCode.RESOURCE_NOT_FOUND]: 'Resource Not Found',
  [ErrorCode.METHOD_NOT_ALLOWED]: 'Method Not Allowed',
  [ErrorCode.AUTH_REQUIRED]: 'Authentication Required',
  [ErrorCode.AUTH_INVALID_TOKEN]: 'Invalid Authentication Token',
  [ErrorCode.AUTH_TOKEN_EXPIRED]: 'Authentication Token Expired',
  [ErrorCode.AUTH_INSUFFICIENT_PERMISSIONS]: 'Insufficient Permissions',
  [ErrorCode.VALIDATION_FAILED]: 'Validation Failed',
  [ErrorCode.VALIDATION_REQUIRED_FIELD]: 'Required Field Missing',
  [ErrorCode.VALIDATION_INVALID_FORMAT]: 'Invalid Format',
  [ErrorCode.VALIDATION_OUT_OF_RANGE]: 'Value Out of Range',
  [ErrorCode.OAUTH2_INVALID_CLIENT]: 'Invalid Client',
  [ErrorCode.OAUTH2_INVALID_GRANT]: 'Invalid Grant',
  [ErrorCode.OAUTH2_INVALID_SCOPE]: 'Invalid Scope',
  [ErrorCode.OAUTH2_INVALID_REDIRECT_URI]: 'Invalid Redirect URI',
  [ErrorCode.OAUTH2_UNSUPPORTED_GRANT_TYPE]: 'Unsupported Grant Type',
};

